name: nodejs-base
region: nyc
services:
- environment_slug: node-js
  git:
    branch: main
    repo_clone_url: https://github.com/mokeseven7/node14-base
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs
  name: nodejs-base
  routes:
  - path: /
  run_command: npm start